=== saurabhsinha9/java-course/XML/XMLDTDTest1/src/com/jlcindia/xml/external/dtd/jlc.dtd
<?xml version="1.0" encoding="UTF-8" ?> 
<!ELEMENT jlc (student,course+)>
<!ELEMENT student (sname,email+,phone?)>
<!ELEMENT course (cname,cost,company)>
<!ATTLIST student sid CDATA #REQUIRED
           bid CDATA #IMPLIED>
<!ELEMENT sname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST course cid CDATA #REQUIRED>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ENTITY comp "Java Learning Center">

=== saurabhsinha9/java-course/XML/XMLDTDTest1/src/com/jlcindia/xml/external/dtd/jlc.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE jlc SYSTEM "jlc.dtd" >
<jlc>
  <student sid="JLC-999" bid="MK-16-252">
  <sname>abc</sname>
  <email>saurabh@jlc</email>
  <email>sa</email>
  <phone>9999</phone>
  </student>
  
  <course cid="56">
  <cname>Java</cname>
  <cost>555</cost>
  <company>&comp;</company>
  </course>
  <course cid="56">
  <cname>Java</cname>
  <cost>555</cost>
  <company>&comp;</company>
  </course>
  <course cid="56">
  <cname>Java</cname>
  <cost>555</cost>
  <company>&comp;</company>
  </course>
</jlc>
