=== saurabhsinha9/java-course/XML/Lab1/src/com/jlcindia/xml/internal/dtd/books.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT books (book*,author+)>
<!ELEMENT book (bname,authorName+,pub,isbn)>
<!ELEMENT author (name,qualification,company)>
<!ATTLIST book bid CDATA #REQUIRED
           free CDATA #IMPLIED >
<!ATTLIST author aid CDATA #REQUIRED>
<!ELEMENT bname (#PCDATA)>
<!ELEMENT authorName (#PCDATA)>
<!ELEMENT pub (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT qualification (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ENTITY comp "Java Learning Center">

=== saurabhsinha9/java-course/XML/Lab1/src/com/jlcindia/xml/internal/dtd/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd" >
<books>
  <book bid="100" free="yes">
    <bname>ANSI C</bname>
    <authorName>E BALAGURUSAMY</authorName>
    <pub>TMH</pub>
    <isbn>ANSI-1234</isbn>
  </book>
  <book bid="100" free="yes">
    <bname>ANSI C</bname>
    <authorName>E BALAGURUSAMY</authorName>
    <authorName>E BALAGURUSAMY</authorName>
    <authorName>E BALAGURUSAMY</authorName>
    <authorName>E BALAGURUSAMY</authorName>
    <pub>TMH</pub>
    <isbn>ANSI-1234</isbn>
  </book>
  <author aid="A-101">
    <name>E BALAGURUSAMY</name>
    <qualification>M.E</qualification>
    <company>&comp;</company>
  </author>
  <author aid="A-101">
    <name>E BALAGURUSAMY</name>
    <qualification>M.E</qualification>
    <company>&comp;</company>
  </author>
</books>
